#!/usr/bin/env python3
"""Emit Sources/CVt/jt_width.inc (2-bit packed widths for U+0000..U+10FFFF).

Pinned to UCD 17.0.0. Inputs live in scripts/unicode/.
"""

from __future__ import annotations

import os
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Sources", "CVt", "jt_width.inc")
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "unicode")
UCD = "https://www.unicode.org/Public/17.0.0/ucd"
NCP = 0x110000


def fetch(name: str) -> str:
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, os.path.basename(name))
    if not os.path.isfile(path):
        url = f"{UCD}/{name}"
        print(f"fetch {url}")
        urllib.request.urlretrieve(url, path)
    with open(path, encoding="utf-8") as f:
        return f.read()


def parse_cps(spec: str) -> range:
    spec = spec.strip()
    if ".." in spec:
        a, b = spec.split("..", 1)
        return range(int(a, 16), int(b, 16) + 1)
    v = int(spec, 16)
    return range(v, v + 1)


def apply_eaw(width: bytearray) -> None:
    text = fetch("EastAsianWidth.txt")
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("# @missing:"):
            body = line[len("# @missing:") :].strip()
            if ";" not in body:
                continue
            spec, rest = body.split(";", 1)
            tag = rest.strip().split()[0]
            if tag in ("W", "F"):
                for cp in parse_cps(spec):
                    if cp < NCP and width[cp] == 1:
                        width[cp] = 2
            continue
        if not line or line.startswith("#"):
            continue
        if ";" not in line:
            continue
        spec, rest = line.split(";", 1)
        tag = rest.split("#", 1)[0].strip()
        if tag in ("W", "F"):
            for cp in parse_cps(spec):
                if cp < NCP:
                    width[cp] = 2


def apply_emoji(width: bytearray) -> None:
    text = fetch("emoji/emoji-data.txt")
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or ";" not in line:
            continue
        spec, prop = line.split(";", 1)
        prop = prop.strip()
        if prop not in ("Emoji_Presentation", "Extended_Pictographic"):
            continue
        for cp in parse_cps(spec):
            if cp < NCP and width[cp] == 1:
                width[cp] = 2


def apply_zero(width: bytearray) -> None:
    text = fetch("UnicodeData.txt")
    for raw in text.splitlines():
        if not raw:
            continue
        fields = raw.split(";")
        cp = int(fields[0], 16)
        if cp >= NCP:
            continue
        cat = fields[2]
        ccc = int(fields[3] or "0")
        if cat in ("Cc", "Cf", "Cs", "Zl", "Zp", "Mn", "Me") or ccc != 0:
            width[cp] = 0
    text = fetch("DerivedCoreProperties.txt")
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or ";" not in line:
            continue
        spec, prop = line.split(";", 1)
        if prop.strip() != "Default_Ignorable_Code_Point":
            continue
        for cp in parse_cps(spec):
            if cp < NCP:
                width[cp] = 0
    for cp in range(0x00, 0x20):
        width[cp] = 0
    width[0x7F] = 0
    for cp in range(0x80, 0xA0):
        width[cp] = 0
    for cp in range(0xD800, 0xE000):
        width[cp] = 0
    width[0x200B] = 0
    width[0x200C] = 0
    width[0x200D] = 0
    width[0x2060] = 0
    width[0xFE0E] = 0
    width[0xFE0F] = 0
    width[0xFEFF] = 0
    for cp in range(0x1F1E6, 0x1F200):
        width[cp] = 2
    # Ghostty clamps 2-em / 3-em dashes to 2 (UAX #11 N, but terminal width 2).
    width[0x2E3A] = 2
    width[0x2E3B] = 2


def pack(width: bytearray) -> bytearray:
    n = NCP // 4
    out = bytearray(n)
    for i in range(n):
        b = 0
        for k in range(4):
            w = width[i * 4 + k]
            if w > 2:
                w = 2
            b |= (w & 3) << (k * 2)
        out[i] = b
    return out


def main() -> None:
    width = bytearray(b"\x01" * NCP)
    apply_eaw(width)
    apply_emoji(width)
    apply_zero(width)
    lut = pack(width)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/gen-width-table.py from UCD 17.0.0. 2 bits per codepoint. */\n")
        f.write(f"const uint8_t jt_width_lut[{len(lut)}] = {{\n")
        for i in range(0, len(lut), 16):
            chunk = lut[i : i + 16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n")
    print(f"wrote {OUT} ({len(lut)} bytes)")


if __name__ == "__main__":
    main()
